# -*- coding: utf-8 -*-
"""Untitled29.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Atn7N5-5jEPN-w73rYqjwMRnUz-oSyx7
"""

import yfinance as yf
import pandas as pd
import numpy as np
from statsmodels.tsa.arima.model import ARIMA
!pip install arch yfinance
from arch import arch_model
from scipy.stats import norm
from sklearn.metrics import confusion_matrix
import itertools
import warnings

# 1. SETUP: Ignore warnings
warnings.filterwarnings("ignore")

def run_market_quant_suite(ticker="AAPL", investment=100000):
    # 2. DATA ACQUISITION
    df = yf.download(ticker, start='2025-05-01', end='2026-05-09', auto_adjust=True)
    if df.empty: return print("Ticker data not found.")

    df['Returns'] = 100 * np.log(df['Close'] / df['Close'].shift(1))
    df = df.dropna()
    data = df['Returns']

    # 3. BACKTEST SPLIT (Last 15 Trading Days)
    test_size = 15
    train_data = data[:-test_size]
    actual_segment = df.iloc[-test_size:]

    # 4. ARIMA GRID SEARCH: Find the best fit automatically
    best_aic, best_order = float("inf"), (1, 0, 0)
    for p, q in itertools.product(range(3), range(3)):
        try:
            mod = ARIMA(train_data, order=(p, 0, q)).fit()
            if mod.aic < best_aic:
                best_aic, best_order = mod.aic, (p, 0, q)
        except: continue

    # 5. BACKTEST PREDICTIONS & ACCURACY CALCULATION
    test_model = ARIMA(train_data, order=best_order).fit()
    pred_returns_test = test_model.forecast(steps=test_size).values.flatten()

    # Calculate Directional Accuracy
    actual_dir = np.where(actual_segment['Returns'] > 0, 1, 0)
    pred_dir = np.where(pred_returns_test > 0, 1, 0)
    cm = confusion_matrix(actual_dir, pred_dir)
    accuracy = (np.trace(cm) / np.sum(cm)) * 100

    last_train_price = df['Close'].iloc[-(test_size + 1)].item()
    pred_prices_test = last_train_price * np.exp(np.cumsum(pred_returns_test) / 100)

    # 6. FUTURE FORECAST & GARCH ENGINE (Next 5 Days)
    final_mod = ARIMA(data, order=best_order).fit()
    model_garch = arch_model(final_mod.resid, p=1, q=1, vol='GARCH', dist='t').fit(disp='off')

    f_mean_arima = final_mod.forecast(steps=5).values.flatten()
    np.random.seed(42)
    current_vol = model_garch.conditional_volatility.iloc[-1] / 2
    noise = np.random.normal(0, current_vol, 5)
    f_mean = f_mean_arima + noise

    f_vol_daily = np.sqrt(model_garch.forecast(horizon=5).variance.values[-1])
    last_actual_price = df['Close'].iloc[-1].item()
    future_prices = last_actual_price * np.exp(np.cumsum(f_mean) / 100)

    # 7. FINANCIAL CALCULATIONS
    ann_vol = f_vol_daily[0] * np.sqrt(252)
    var_val = investment * norm.ppf(0.95) * (f_vol_daily[0] / 100)
    npv = sum([(investment * (r/100)) / (1.00047)**(i+1) for i, r in enumerate(f_mean)])
    profit_ratio = (npv / var_val) if var_val != 0 else 0

    # 8. FINAL OUTPUT (Matching your Terminal Image style)
    print(f"\n{'='*75}\n FINAL QUANTITATIVE REPORT: {ticker.upper()}\n{'='*75}")

    print(f"--- BACKTEST COMPARISON (LAST {test_size} DAYS) ---")
    comp_df = pd.DataFrame({
        'Actual Price': actual_segment['Close'].values.flatten(),
        'Pred Price': pred_prices_test.flatten(),
        'Actual %': actual_segment['Returns'].values.flatten(),
        'Pred %': pred_returns_test.flatten()
    }, index=actual_segment.index)
    print(comp_df.round(4))

    print(f"\n--- FUTURE 5-DAY FORECAST ---")
    future_dates = pd.date_range(start=df.index[-1], periods=6, freq='B')[1:]
    future_df = pd.DataFrame({
        'Forecast Price': future_prices.flatten(),
        'Expected Return %': f_mean.flatten()
    }, index=future_dates)
    print(future_df.round(4))

    # ADDED SECTION: MODEL PERFORMANCE
    print(f"\n--- MODEL PERFORMANCE ---")
    print(f"Optimal ARIMA Order: {best_order}")
    print(f"Directional Accuracy: {accuracy:.2f}%")

    print(f"\n--- FINANCIALS & RISK (GARCH) ---")
    print(f"GARCH Annualized Volatility: {ann_vol:.2f}%")
    print(f"Value at Risk (VaR 95%): PKR {var_val:,.2f}")
    print(f"Net Present Value (NPV): PKR {npv:,.2f}")
    print(f"Profit-to-Risk Ratio: {profit_ratio:.4f}")

    print(f"\n--- EXECUTION VERDICT ---")
    if npv > 0 and profit_ratio > 0.15:
        print(f">>> STRONG BUY: Ratio {profit_ratio:.2f} is above 0.15 threshold.")
    elif npv > 0:
        print(f">>> HOLD: Positive NPV but Ratio {profit_ratio:.2f} is below 0.15.")
    else:
        print(">>> SELL/AVOID: Expected value is negative.")
    print(f"{'='*75}")

run_market_quant_suite("AAPL")